
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import LayoutWrapper from "@/component/LayoutWrapper";
import { cookies } from "next/headers";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const shabnam = localFont({
    src: [
        {
            path: "../assets/fonts/shabnam/Farsi-Digits-Without-Latin/Shabnam-Bold-FD-WOL.woff2",
            weight: "700",
            style: "normal",
        },
    ],
    variable: "--font-shabnam",
});

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const cookieStore = await cookies()

    const token = cookieStore.get('accessToken')

    const isLoggedIn = !!token?.value
    return (
        <html lang="en">
            <body className={shabnam.className}>
                <Providers>
                    <LayoutWrapper isLoggedIn={isLoggedIn}>
                        {children}
                        <Toaster position="top-center" />
                    </LayoutWrapper>
                </Providers>
            </body>
        </html>
    );
}
